spring:
  datasource:
    url: jdbc:mysql://139.180.196.97:3306/yxchange?characterEncoding=utf8&useSSL=false
    username: admin
    password: 'admin@2018!'
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 139.180.196.97
    port: 6379
    password: 'vultr@redis!'
mybatis:
  type-aliases-package: com.github.yxchange.metadata
  mapper-locations: classpath:mybatis_mapper/*.xml
mapper:
  IDENTITY: MYSQL
  order: after
logging:
  level:
    root: INFO
    org.mybatis: DEBUG
    com.github.yxchange: DEBUG
server:
  port: 9090
dubbo:
  application:
    name: match-engin
    qos:
      port: 22223
  registry:
    address: zookeeper://139.180.196.97:2181
  protocol:
    name: dubbo
    port: 28081
  