spring:
  datasource:
    url: jdbc:mysql://13.114.202.163:3306/yxchange?characterEncoding=utf8&useSSL=false
    username: admin
    password: 'viewfin@2018^&*'
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 13.114.202.163
    port: 6379
    password: testdevpass
mybatis:
  type-aliases-package: com.github.yxchange.metadata
  mapper-locations: classpath:mybatis_mapper/*.xml
mapper:
  IDENTITY: MYSQL
  order: after
logging:
  level:
    root: INFO
    org.mybatis: DEBUG
    com.github.yxchange: DEBUG