spring:
  datasource:
    url: jdbc:mysql://13.114.202.163:3306/yxchange?characterEncoding=utf8
    username: admin
    password: 'viewfin@2018^&*'
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.github.yxchange.metadata
  mapper-locations: classpath:mybatis_mapper/*.xml
mapper:
  IDENTITY: MYSQL
  order: after